# Generated by Django 3.2.9 on 2023-05-28 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBlock',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('vo', 'Voice Over'), ('bg_music', 'Background Music'), ('video_music', 'Video Music')], max_length=20)),
                ('high_volume', models.IntegerField()),
                ('low_volume', models.IntegerField()),
                ('url', models.URLField(blank=True, null=True)),
                ('duration_start_time', models.IntegerField(blank=True, null=True)),
                ('duration_end_time', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoBlock',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('duration_start_time', models.IntegerField()),
                ('duration_end_time', models.IntegerField()),
                ('audio_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.audioblock')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_blocks', models.ManyToManyField(to='api.AudioBlock')),
                ('video_blocks', models.ManyToManyField(to='api.VideoBlock')),
            ],
        ),
        migrations.AddField(
            model_name='audioblock',
            name='video_component_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.videoblock'),
        ),
    ]
