# Generated by Django 3.2.9 on 2023-05-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioblock',
            name='duration_end_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audioblock',
            name='duration_start_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
