# Generated by Django 3.2.9 on 2023-05-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230528_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioblock',
            name='duration_end_time',
        ),
        migrations.RemoveField(
            model_name='audioblock',
            name='duration_start_time',
        ),
        migrations.AlterField(
            model_name='videoblock',
            name='duration_end_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='videoblock',
            name='duration_start_time',
            field=models.DurationField(),
        ),
    ]
