# Generated by Django 3.2.9 on 2023-05-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230530_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoblock',
            name='duration_end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='videoblock',
            name='duration_start_time',
            field=models.IntegerField(),
        ),
    ]
