# Generated by Django 3.2.9 on 2023-05-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230530_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioblock',
            name='duration_end_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioblock',
            name='duration_start_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
